echo("<!doctype html>");
echo("<html>");
echo("<head>");
echo("<meta charset=\"utf-8\">");
echo("<title>404</title>");
echo("");
echo("<script type=\"text/javascript\" src=\"https://a-oss.zmki.cn/2020/20200101-cc0f0c1509531.js\"></script>");
echo("");
echo("<style>");
echo("html, body {");
echo("  background: #28254C;");
echo("  font-family: \'Ubuntu\';");
echo("}");
echo("");
echo("* {");
echo("  box-sizing: border-box;");
echo("}");
echo("");
echo(".box {");
echo("  width: 350px;");
echo("  height: 100%;");
echo("  max-height: 600px;");
echo("  min-height: 450px;");
echo("  background: #332F63;");
echo("  border-radius: 20px;");
echo("  position: absolute;");
echo("  left: 50%;");
echo("  top: 50%;");
echo("  transform: translate(-50%, -50%);");
echo("  padding: 30px 50px;");
echo("}");
echo(".box .box__ghost {");
echo("  padding: 15px 25px 25px;");
echo("  position: absolute;");
echo("  left: 50%;");
echo("  top: 30%;");
echo("  transform: translate(-50%, -30%);");
echo("}");
echo(".box .box__ghost .symbol:nth-child(1) {");
echo("  opacity: .2;");
echo("  animation: shine 4s ease-in-out 3s infinite;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(1):before, .box .box__ghost .symbol:nth-child(1):after {");
echo("  content: \'\';");
echo("  width: 12px;");
echo("  height: 4px;");
echo("  background: #fff;");
echo("  position: absolute;");
echo("  border-radius: 5px;");
echo("  bottom: 65px;");
echo("  left: 0;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(1):before {");
echo("  transform: rotate(45deg);");
echo("}");
echo(".box .box__ghost .symbol:nth-child(1):after {");
echo("  transform: rotate(-45deg);");
echo("}");
echo(".box .box__ghost .symbol:nth-child(2) {");
echo("  position: absolute;");
echo("  left: -5px;");
echo("  top: 30px;");
echo("  height: 18px;");
echo("  width: 18px;");
echo("  border: 4px solid;");
echo("  border-radius: 50%;");
echo("  border-color: #fff;");
echo("  opacity: .2;");
echo("  animation: shine 4s ease-in-out 1.3s infinite;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(3) {");
echo("  opacity: .2;");
echo("  animation: shine 3s ease-in-out .5s infinite;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(3):before, .box .box__ghost .symbol:nth-child(3):after {");
echo("  content: \'\';");
echo("  width: 12px;");
echo("  height: 4px;");
echo("  background: #fff;");
echo("  position: absolute;");
echo("  border-radius: 5px;");
echo("  top: 5px;");
echo("  left: 40px;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(3):before {");
echo("  transform: rotate(90deg);");
echo("}");
echo(".box .box__ghost .symbol:nth-child(3):after {");
echo("  transform: rotate(180deg);");
echo("}");
echo(".box .box__ghost .symbol:nth-child(4) {");
echo("  opacity: .2;");
echo("  animation: shine 6s ease-in-out 1.6s infinite;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(4):before, .box .box__ghost .symbol:nth-child(4):after {");
echo("  content: \'\';");
echo("  width: 15px;");
echo("  height: 4px;");
echo("  background: #fff;");
echo("  position: absolute;");
echo("  border-radius: 5px;");
echo("  top: 10px;");
echo("  right: 30px;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(4):before {");
echo("  transform: rotate(45deg);");
echo("}");
echo(".box .box__ghost .symbol:nth-child(4):after {");
echo("  transform: rotate(-45deg);");
echo("}");
echo(".box .box__ghost .symbol:nth-child(5) {");
echo("  position: absolute;");
echo("  right: 5px;");
echo("  top: 40px;");
echo("  height: 12px;");
echo("  width: 12px;");
echo("  border: 3px solid;");
echo("  border-radius: 50%;");
echo("  border-color: #fff;");
echo("  opacity: .2;");
echo("  animation: shine 1.7s ease-in-out 7s infinite;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(6) {");
echo("  opacity: .2;");
echo("  animation: shine 2s ease-in-out 6s infinite;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(6):before, .box .box__ghost .symbol:nth-child(6):after {");
echo("  content: \'\';");
echo("  width: 15px;");
echo("  height: 4px;");
echo("  background: #fff;");
echo("  position: absolute;");
echo("  border-radius: 5px;");
echo("  bottom: 65px;");
echo("  right: -5px;");
echo("}");
echo(".box .box__ghost .symbol:nth-child(6):before {");
echo("  transform: rotate(90deg);");
echo("}");
echo(".box .box__ghost .symbol:nth-child(6):after {");
echo("  transform: rotate(180deg);");
echo("}");
echo(".box .box__ghost .box__ghost-container {");
echo("  background: #fff;");
echo("  width: 100px;");
echo("  height: 100px;");
echo("  border-radius: 100px 100px 0 0;");
echo("  position: relative;");
echo("  margin: 0 auto;");
echo("  animation: upndown 3s ease-in-out infinite;");
echo("}");
echo(".box .box__ghost .box__ghost-container .box__ghost-eyes {");
echo("  position: absolute;");
echo("  left: 50%;");
echo("  top: 45%;");
echo("  height: 12px;");
echo("  width: 70px;");
echo("}");
echo(".box .box__ghost .box__ghost-container .box__ghost-eyes .box__eye-left {");
echo("  width: 12px;");
echo("  height: 12px;");
echo("  background: #332F63;");
echo("  border-radius: 50%;");
echo("  margin: 0 10px;");
echo("  position: absolute;");
echo("  left: 0;");
echo("}");
echo(".box .box__ghost .box__ghost-container .box__ghost-eyes .box__eye-right {");
echo("  width: 12px;");
echo("  height: 12px;");
echo("  background: #332F63;");
echo("  border-radius: 50%;");
echo("  margin: 0 10px;");
echo("  position: absolute;");
echo("  right: 0;");
echo("}");
echo(".box .box__ghost .box__ghost-container .box__ghost-bottom {");
echo("  display: flex;");
echo("  position: absolute;");
echo("  top: 100%;");
echo("  left: 0;");
echo("  right: 0;");
echo("}");
echo(".box .box__ghost .box__ghost-container .box__ghost-bottom div {");
echo("  flex-grow: 1;");
echo("  position: relative;");
echo("  top: -10px;");
echo("  height: 20px;");
echo("  border-radius: 100%;");
echo("  background-color: #fff;");
echo("}");
echo(".box .box__ghost .box__ghost-container .box__ghost-bottom div:nth-child(2n) {");
echo("  top: -12px;");
echo("  margin: 0 -0px;");
echo("  border-top: 15px solid #332F63;");
echo("  background: transparent;");
echo("}");
echo(".box .box__ghost .box__ghost-shadow {");
echo("  height: 20px;");
echo("  box-shadow: 0 50px 15px 5px #3B3769;");
echo("  border-radius: 50%;");
echo("  margin: 0 auto;");
echo("  animation: smallnbig 3s ease-in-out infinite;");
echo("}");
echo(".box .box__description {");
echo("  position: absolute;");
echo("  bottom: 30px;");
echo("  left: 50%;");
echo("  transform: translateX(-50%);");
echo("}");
echo(".box .box__description .box__description-container {");
echo("  color: #fff;");
echo("  text-align: center;");
echo("  width: 200px;");
echo("  font-size: 16px;");
echo("  margin: 0 auto;");
echo("}");
echo(".box .box__description .box__description-container .box__description-title {");
echo("  font-size: 24px;");
echo("  letter-spacing: .5px;");
echo("}");
echo(".box .box__description .box__description-container .box__description-text {");
echo("  color: #8C8AA7;");
echo("  line-height: 20px;");
echo("  margin-top: 20px;");
echo("}");
echo(".box .box__description .box__button {");
echo("  display: block;");
echo("  position: relative;");
echo("  background: #FF5E65;");
echo("  border: 1px solid transparent;");
echo("  border-radius: 50px;");
echo("  height: 50px;");
echo("  text-align: center;");
echo("  text-decoration: none;");
echo("  color: #fff;");
echo("  line-height: 50px;");
echo("  font-size: 18px;");
echo("  padding: 0 70px;");
echo("  white-space: nowrap;");
echo("  margin-top: 25px;");
echo("  transition: background .5s ease;");
echo("  overflow: hidden;");
echo("}");
echo(".box .box__description .box__button:before {");
echo("  content: \'\';");
echo("  position: absolute;");
echo("  width: 20px;");
echo("  height: 100px;");
echo("  background: #fff;");
echo("  bottom: -25px;");
echo("  left: 0;");
echo("  border: 2px solid #fff;");
echo("  transform: translateX(-50px) rotate(45deg);");
echo("  transition: transform .5s ease;");
echo("}");
echo(".box .box__description .box__button:hover {");
echo("  background: transparent;");
echo("  border-color: #fff;");
echo("}");
echo(".box .box__description .box__button:hover:before {");
echo("  transform: translateX(250px) rotate(45deg);");
echo("}");
echo("");
echo("@keyframes upndown {");
echo("  0% {");
echo("    transform: translateY(5px);");
echo("  }");
echo("  50% {");
echo("    transform: translateY(15px);");
echo("  }");
echo("  100% {");
echo("    transform: translateY(5px);");
echo("  }");
echo("}");
echo("@keyframes smallnbig {");
echo("  0% {");
echo("    width: 90px;");
echo("  }");
echo("  50% {");
echo("    width: 100px;");
echo("  }");
echo("  100% {");
echo("    width: 90px;");
echo("  }");
echo("}");
echo("@keyframes shine {");
echo("  0% {");
echo("    opacity: .2;");
echo("  }");
echo("  25% {");
echo("    opacity: .1;");
echo("  }");
echo("  50% {");
echo("    opacity: .2;");
echo("  }");
echo("  100% {");
echo("    opacity: .2;");
echo("  }");
echo("}");
echo("</style>");
echo("</head>");
echo("<body>");
echo("<div class=\"box\">");
echo("  <div class=\"box__ghost\">");
echo("    <div class=\"symbol\"></div>");
echo("    <div class=\"symbol\"></div>");
echo("    <div class=\"symbol\"></div>");
echo("    <div class=\"symbol\"></div>");
echo("    <div class=\"symbol\"></div>");
echo("    <div class=\"symbol\"></div>");
echo("    ");
echo("    <div class=\"box__ghost-container\">");
echo("      <div class=\"box__ghost-eyes\">");
echo("        <div class=\"box__eye-left\"></div>");
echo("        <div class=\"box__eye-right\"></div>");
echo("      </div>");
echo("      <div class=\"box__ghost-bottom\">");
echo("        <div></div>");
echo("        <div></div>");
echo("        <div></div>");
echo("        <div></div>");
echo("        <div></div>");
echo("      </div>");
echo("    </div>");
echo("    <div class=\"box__ghost-shadow\"></div>");
echo("  </div>");
echo("  ");
echo("  <div class=\"box__description\">");
echo("    <div class=\"box__description-container\">");
echo("      <div class=\"box__description-title\">404错误！</div>");
echo("      <div class=\"box__description-text\">看来我们找不到你要找的那一页</div>");
echo("    </div>");
echo("    ");
echo("    <a href=\"https://mohuajz.github.io/index.html\" class=\"box__button\">主页</a>");
echo("    ");
echo("  </div>");
echo("  ");
echo("</div>");
echo("");
echo("<script>");
echo("//based on https://dribbble.com/shots/3913847-404-page");
echo("");
echo("var pageX = $(document).width();");
echo("var pageY = $(document).height();");
echo("var mouseY=0;");
echo("var mouseX=0;");
echo("");
echo("$(document).mousemove(function( event ) {");
echo("  //verticalAxis");
echo("  mouseY = event.pageY;");
echo("  yAxis = (pageY/2-mouseY)/pageY*300; ");
echo("  //horizontalAxis");
echo("  mouseX = event.pageX / -pageX;");
echo("  xAxis = -mouseX * 100 - 100;");
echo("");
echo("  $(\'.box__ghost-eyes\').css({ \'transform\': \'translate(\'+ xAxis +\'%,-\'+ yAxis +\'%)\' }); ");
echo("");
echo("  //console.log(\'X: \' + xAxis);");
echo("");
echo("});</script>");
echo("");
echo("</body>");
echo("</html>");
